# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := p200
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := p200
TARGET_BOARD_PLATFORM_GPU := mali-450

# Architecture
#TARGET_ARCH := arm64
#TARGET_ARCH_VARIANT := armv8-a
#TARGET_CPU_ABI := arm64-v8a
#TARGET_CPU_ABI2 :=
#TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic

#TARGET_2ND_ARCH := arm
#TARGET_2ND_ARCH_VARIANT := armv7-a-neon
#TARGET_2ND_CPU_ABI := armeabi-v7a
#TARGET_2ND_CPU_ABI2 := armeabi
#TARGET_2ND_CPU_VARIANT := generic

BOARD_KERNEL_CMDLINE :=

BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x01080000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --second device/minix/p200_2G/dtb

# prebuilt kernel
TARGET_PREBUILT_KERNEL := device/minix/p200_2G/kernel
# else uncomment below to build from sauce
# TARGET_KERNEL_SOURCE := kernel/minix/p200_2G
# TARGET_KERNEL_CONFIG := p200_2G_defconfig

BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/

TW_THEME := landscape_hdpi
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_SCREEN_TIMEOUT := true
TW_BRIGHTNESS_PATH := "/brightness"
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
